In [2]:
#Consulta de pandas en: https://pydata.github.io/pandas-datareader/remote_data.html#oecd
#Acceso a base de datos de la OECD
#Indice de datasets de OECD en 
#http://sdmx.herokuapp.com/OECD/dataflow

import pandas_datareader.data as web
import datetime
import datetime as dt
from pandas.util.testing import assert_frame_equal

# Paso 1. Indicar el dataset de OECD a extraer 
df = web.DataReader('CTS_CIT', 'oecd')
df.columns

MultiIndex([('Democratic Republic of the Congo', ...),
            ('Democratic Republic of the Congo', ...),
            ('Democratic Republic of the Congo', ...),
            ('Democratic Republic of the Congo', ...),
            ('Democratic Republic of the Congo', ...),
            (                          'Monaco', ...),
            (                          'Monaco', ...),
            (                          'Monaco', ...),
            (                          'Monaco', ...),
            (                          'Monaco', ...),
            ...
            (                        'Slovenia', ...),
            (                        'Slovenia', ...),
            (                        'Slovenia', ...),
            (                        'Slovenia', ...),
            (                        'Slovenia', ...),
            (                'Hong Kong, China', ...),
            (                'Hong Kong, China', ...),
            (                'Hong Kong, China', ...),
            (                'Hong Kong, China', ...),
            (                'Hong Kong, China', ...)],
           names=['Country', 'Corporate income tax rate'], length=470)

In [3]:
#Paso 2. Verificar la informaciÃ³n a obtener, mediante consulta especÃ­fica

#Consulta especÃ­fica de prueba para Dataset 'TUD', 'CTS_CIT', 'ITF_INDICATORS', 'LAND_USE', 'INSIND', 'DUR_D'
df[['Spain', 'Japan', 'France', 'Canada', 'Sweden', 'Germany']]

#Consulta especÃ­fica de prueba para Dataset REVMEX
#df[['Total tax revenue on cash basis']]

#Consulta especÃ­fica de prueba para Dataset AWCOU
#df[['Total gross earnings before taxes']]

Country                                                                              Spain  \
Corporate income tax rate Corporate income tax rate less deductions for sub-national taxes
Year
2016-01-01                                                              25.0
2017-01-01                                                              25.0
2018-01-01                                                              25.0

Country                                              \
Corporate income tax rate Corporate income tax rate
Year
2016-01-01                                     25.0
2017-01-01                                     25.0
2018-01-01                                     25.0

Country                                                       \
Corporate income tax rate Combined corporate income tax rate
Year
2016-01-01                                              25.0
2017-01-01                                              25.0
2018-01-01                                              25.0

Country                                                                     \
Corporate income tax rate Sub-central government corporate income tax rate
Year
2016-01-01                                                             NaN
2017-01-01                                                             NaN
2018-01-01                                                             NaN

Country                                                                  \
Corporate income tax rate Corporate income tax rate exclusive of surtax
Year
2016-01-01                                                          NaN
2017-01-01                                                          NaN
2018-01-01                                                          NaN

Country                                                                              Japan  \
Corporate income tax rate Corporate income tax rate less deductions for sub-national taxes
Year
2016-01-01                                                             22.59
2017-01-01                                                             22.59
2018-01-01                                                             22.39

Country                                              \
Corporate income tax rate Corporate income tax rate
Year
2016-01-01                                     23.4
2017-01-01                                     23.4
2018-01-01                                     23.2

Country                                                       \
Corporate income tax rate Combined corporate income tax rate
Year
2016-01-01                                             29.97
2017-01-01                                             29.97
2018-01-01                                             29.74

Country                                                                     \
Corporate income tax rate Sub-central government corporate income tax rate
Year
2016-01-01                                                            7.38
2017-01-01                                                            7.38
2018-01-01                                                            7.35

Country                                                                  ...  \
Corporate income tax rate Corporate income tax rate exclusive of surtax  ...
Year                                                                     ...
2016-01-01                                                          NaN  ...
2017-01-01                                                          NaN  ...
2018-01-01                                                          NaN  ...

Country                                                                             Sweden  \
Corporate income tax rate Corporate income tax rate less deductions for sub-national taxes
Year
2016-01-01                                                              22.0
2017-01-01                                                              22.0
2018-01-01                                                              22.0

Country                                              \
Corporate income tax rate Corporate income tax rate
Year
2016-01-01                                     22.0
2017-01-01                                     22.0
2018-01-01                                     22.0

Country                                                       \
Corporate income tax rate Combined corporate income tax rate
Year
2016-01-01                                              22.0
2017-01-01                                              22.0
2018-01-01                                              22.0

Country                                                                     \
Corporate income tax rate Sub-central government corporate income tax rate
Year
2016-01-01                                                             NaN
2017-01-01                                                             NaN
2018-01-01                                                             NaN

Country                                                                  \
Corporate income tax rate Corporate income tax rate exclusive of surtax
Year
2016-01-01                                                          NaN
2017-01-01                                                          NaN
2018-01-01                                                          NaN

Country                                                                            Germany  \
Corporate income tax rate Corporate income tax rate less deductions for sub-national taxes
Year
2016-01-01                                                            15.825
2017-01-01                                                            15.825
2018-01-01                                                            15.825

Country                                              \
Corporate income tax rate Corporate income tax rate
Year
2016-01-01                                   15.825
2017-01-01                                   15.825
2018-01-01                                   15.825

Country                                                       \
Corporate income tax rate Combined corporate income tax rate
Year
2016-01-01                                            29.825
2017-01-01                                            29.825
2018-01-01                                            29.825

Country                                                                     \
Corporate income tax rate Sub-central government corporate income tax rate
Year
2016-01-01                                                            14.0
2017-01-01                                                            14.0
2018-01-01                                                            14.0

Country
Corporate income tax rate Corporate income tax rate exclusive of surtax
Year
2016-01-01                                                         15.0
2017-01-01                                                         15.0
2018-01-01                                                         15.0

[3 rows x 30 columns]

In [4]:
#Paso 3. Descargar la informaciÃ³n en formato CSV 
#ExportaciÃ³n a archivo de texto
df.to_csv('C:\\Users\\Intel\\Documents\\Mis documentos IDEA\\Samples\\Archivos fuente.ILB\\oecd_.csv',sep = ";")